version: '3.6'
services:
  mysql:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
      - TZ=America/Toronto

  postgres:
    image: postgres:11.1
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: root

  test:
    volumes:
      - .:/var/app
    depends_on:
      - kafka-broker
      - mysql
      - postgres
    build: .
    environment:
      - "DEFAULT_TIMEOUT=${DEFAULT_TIMEOUT}"
      - MYSQL_HOST=mysql
      - PG_HOST=postgres
      - SCHEMA_REGISTRY=http://schema-registry:8081
      - KAFKA_SEED_BROKER=kafka-broker:9092
    command: dockerize -wait tcp://mysql:3306 -wait tcp://postgres:5432 -timeout 1m rspec

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
     - 2181:2181

  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka-broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  kafka-broker:
    image: confluentinc/cp-enterprise-kafka
    hostname: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

